[package]
name = "ectoken"
version = "0.1.0"
authors = ["Benoît Burnichon <bburnichon@gmail.com>"]
edition = "2018"
description = "Token Generator for Edgecast Token-Based Authentication from Verizon Digital Media Services"
license = "MIT or Apache-2.0"

[dependencies]
base64 = "^0.10"
rand = "^0.6" 
rust-crypto = "^0.2"
